#!/usr/bin/env bash

eval "$(ssh-agent -s)"

# Get the latest changes.
git fetch origin

git remote add dokku-prod dokku@dokku.goodforpocin.tech:api-prod
git remote add dokku-staging dokku@dokku.goodforpocin.tech:api-staging

git push "dokku-$1" "${TRAVIS_COMMIT}:master"
